### ISSUE TITLE
Module Request: Decimator Designs UCP Control

### ISSUE THREAD

**Issue by aaronkothe** [bitfocus/companion-module-requests#83]
**Describe the feature**
Decimator Designs manufactures a variety of converters, splitters, and multi-viewers for video production. Their products are widely regarded as some of the most capable and reliable in the industry.

Most of Decimator's products are controlled by a single, simple (at least for the user) software program, called UCP (current version 2.0.11). Plug in one of their products via USB, 'scan' for hardware, and the options for your Decimator device are displayed.

It would be amazing if Companion could enable Streamdeck to control the UCP software!

**Is this platform dependent (windows, mac, ..)?**
I don't believe so - the software is available for Mac & Windows.

**If documentation is required to implement, do you know where to find it?**
Unfortunately, I know next to nothing about coding, so I don't know what might be helpful for the devs. Here's the link to the download page for UCP: http://decimator.com/DOWNLOADS/DOWNLOADS.html

**Usecases**
The specific use case I envision is with a multi-viewer. Decimator's DMON-QUAD allows customizable presets for multi-view layouts, i.e. having three video inputs displayed one way with another input displayed a different way. The ability to live-switch between these presets using the Streamdeck would be immensely powerful, basically making a super advanced feature only available on very expensive (five figures plus) replicable with something like a basic BMD ATEM, a computer, and a Streamdeck.

This is far from the only use case, though. Decimator makes their products very configurable, so control commands could be created to do all sorts of things depending on the product.

Thank you guys for all you do!

**Comment by quentinmit** [comment]
@haakonnessjoen It's been a while, so it's worth pinging again. Have you had any luck figuring out how to get libftdi working in Companion?

**Comment by QuentinBrown** [comment]
I would also love to hear of anymore progress on this. I just learnt about companion and bought a stream deck and this is the missing key for me to the ideal system control button setup.

Last real update was that we need to see if it is possible to compile fdti libs as posted by haakonnessjoen

> So the first we need to do, is to check how hard it is to get ftdi libs to compile on all supported platforms/operating systems of companion. So I might just do a simle ftdi test later today with the build servers. If this is hard, we need to think about a solution where the driver-part is an external application, and then companion connects to it via network.

But no update as to how anyone has got on with that to know if this can move forward.

**Comment by alvarusan** [comment]
Hi everyone, just checking if it has it been any progress on this?

**Comment by quentinmit** [comment]
@josephdadams AFAIK the only remaining work to support this is within the Companion project; that doesn't sound like "blocked externally" to me?

**Comment by josephdadams** [comment]
I can remove that label if you want, but I believe the status remains the same, cross platform compatibility of the ftdi libraries needs to be figured out.

**Comment by quentinmit** [comment]
That's my understanding as well; the libraries themselves are already cross-platform, someone within the Companion project needs to figure out how to incorporate them into the build process (and then also translate the Python to JavaScript, I guess)

**Comment by alvarusan** [comment]
> That's my understanding as well; the libraries themselves are already cross-platform, someone within the Companion project needs to figure out how to incorporate them into the build process (and then also translate the Python to JavaScript, I guess)

Does it means that is all about the Companion team now?

**Comment by quentinmit** [comment]
> > That's my understanding as well; the libraries themselves are already cross-platform, someone within the Companion project needs to figure out how to incorporate them into the build process (and then also translate the Python to JavaScript, I guess)
> 
> Does it means that is all about the Companion team now?

Yes, that's what it means. (It was true back in April of last year, too).

**Comment by josephdadams** [comment]
You guys could always consider making a separate application that’s controllable over the network by Companion. Or submit a pull request that does what you want!

**Comment by quentinmit** [comment]
FYI I've updated decimctl to add support for the 12G-CROSS now.

I've already asked multiple times if there is precedent for out-of-process drivers, and what protocol to use, and I have not gotten a reply. I've done all the reverse engineering necessary; if y'all don't want to actually help get it merged into Companion, there's not much I can do.

**Comment by haakonnessjoen** [comment]
If you could create a stand-alone application that exposes the api via a simple network protocol. It would be a lot simpler for anyone to create a fitting module in companion to control the devices. We try to keep companion mostly for network related software and products, and are not too happy about usb-devices, although there have been a few exceptions.

If there was an application in between, converting the usb-interaction to network, this would solve it. If you or someone could do a simple open source, multi platform python application. Companion could be it's companion.

In regards of the protocol between companion and this application, just do it as simple as can be without restricting any functinality :)

**Comment by aaronkothe** [comment]
I'm glad to see people are still working/thinking about this.

I'll ask again - who and how much do I need to pay to make this happen? I got it working back in the day with some complicated scripts and hotkey listeners, but it was so much work each time, I haven't used it since.

**Comment by alvarusan** [comment]
I don't know either, but I can help to find the persone if someone can address the kind of programmer that needs to do this: “create a stand-alone application that exposes the api via a simple network protocol”?
Is it a python programmer?

Thank you all

> I'm glad to see people are still working/thinking about this.
> 
> I'll ask again - who and how much do I need to pay to make this happen? I got it working back in the day with some complicated scripts and hotkey listeners, but it was so much work each time, I haven't used it since.

**Comment by haakonnessjoen** [comment]
Since the code written by @quentinmit is in python, the easiest would be to have a python programmer create that application yes. Maybe he even wants to do it himself, if someone flashes some money?

**Comment by QuentinBrown** [comment]
Would it also be a possible solution worth exploring to ask Decimator
Design if they would consider implementing a simple network protocol for
control in UCP itself?

I know we have gone down this road in some way before in asking them to
provide a fully documented API for the hardware and they have not been
interested due to the perceived cost vs business benefit ratio, but would
adding a simple network protocol into UCP likely be a much cheaper and
easier option for them to implement? Maybe we could even set up a go fund
me or something if they can cost it up?

Please excuse me if this is naive thinking on my part, I have only the
vaguest of notions of what might be involved in development, but I'd think
not having to reverse engineer the USB protocols for all their devices
would make it a lot cheaper.

**Comment by alvarusan** [comment]
Decimator Design hasn't been responsive at all about any requests or feedback, so I guess that's kind of out of the table.

@quentinmit Is creating a stand-alone application that exposes the api via a simple network protocol something you know how to do? or if it's someone else, does she/he needs to translate your script from Python to Javascript first?

**Comment by henryflorence** [comment]
Hey guys, just found this thread as I'm interested in controlling a DMON-6S from companion.

We already control VICREO hotkey and of greater relavence midi-relay. Both of these are external programs, controlled via a network protocol. Midi-relay is implemented in Node.js (same as companion), but a python version of this for Decimator-relay seems like a very elegant solution.

**Comment by josephdadams** [comment]
Yes, that is what we suggested to the developer of the Python code, to make it a standalone project that accepts API commands from Companion over the network. Until that’s done, this likely isn’t progressing further.

**Comment by aaronkothe** [comment]
@quentinmit please let me know how much you'd charge to create what folks have suggested, "a stand-alone application that exposes the API via a simple network protocol." You can contact me directly agkothe@live.com. And if you aren't interested, do we have everything we need to ask someone else to do it?

**Comment by quentinmit** [comment]
It's open source; you're welcome to take the library I wrote and wrap it in whatever program/protocol you want. I think you have everything you should need for any Python developer to do that.

I don't really want to invent a bespoke protocol for this; I may still implement OSC, but Companion doesn't really have bidirectional OSC support that would give proper feedback. I'm not interested in being paid for development, sorry.

You can also use my code as-is without any changes at all if you use the "Run shell path" action. Again that would be without any feedback information.

**Comment by aaronkothe** [comment]
No apologies necessary. We wouldn't even be this far without you.

**Comment by felixdreinulldrei** [comment]
Hi,
@quentinmit thanks for your great work! I was succesful making it work on my Mac (High Sierra) but unfortunately I was not able to make it work on Linux Ubuntu(18.04). And I'm not able to figure out what the reason is.
I have tried on a real Linux Machine and on VM with same result.
These are the Library Versions which where installed using apt and pip. I was not able to specify a specific version for installation.

libftdi-dev  version 0.20-4
pylibftdi version 0.19.0
libusb-dev version 2:0.1.12-32

connecting my MD-HX this is what I get:

`
felix@myUbuntu:~/decimctl/bin $ ./decimctl list  `
`
Traceback (most recent call last):`
`  File "./decimctl", line 118, in <module>`
`    main()`
`  File "./decimctl", line 115, in main`
`    args.func(args)`
`  File "./decimctl", line 11, in list_devices`
`    devices = decimctl.list_devices()`
`  File "/home/felix/.local/lib/python3.7/site-packages/decimctl/__init__.py", line 44, in list_devices`
`    return pylibftdi.driver.Driver().list_devices()`
`  File "/home/felix/.local/lib/python3.7/site-packages/pylibftdi/driver.py", line 237, in list_devices`
`    raise FtdiError(msg)`
`pylibftdi._base.FtdiError: b'libusb_open() failed' (-4)`

and this is the output doing the same as sudo

`
felix@myUbuntu:~/decimctl/bin $ sudo ./decimctl list`
`Traceback (most recent call last):`
 ` File "./decimctl", line 4, in <module>`
 `   import decimctl`
`ModuleNotFoundError: No module named 'decimctl'
`
Does anybody knows the reason for this behavior or anybody here succesfully made it work on Linux?

**Comment by quentinmit** [comment]
@felixdreinulldrei  I would guess that's indeed a permissions problem; if you want to run it as root you'll also need to install it as root. (So `sudo python setup.py install` or the like.) If you want to run it as a user on Linux, you'll need to edit your udev configuration to give that user permission to manipulate the device. You could use a udev rule like the following to give any user permission on the device:

```
ACTION=="add", ATTRS{idVendor}=="0x215f", MODE="0666"
```

I looked for but couldn't find any good, simple documentation to point you to for writing udev rules to change permissions, unfortunately.

**Comment by felixdreinulldrei** [comment]
@quentinmit meanwhile I have tried different ways. Also with udev rules. 
I have also tried it with Debain 10.  
While both distributions are working fine with the command "decimctl list" . 
The command "decimctl status" always outputs.

`Traceback (most recent call last):  `
`  File "bin/decimctl", line 118, in <module>  `
`    main()  `
`  File "bin/decimctl", line 115, in main  `
 `   args.func(args)`
`  File "bin/decimctl", line 26, in status`
`    d = _create_device(args)`
`  File "bin/decimctl", line 19, in _create_device`
`    return decimctl.Device(log_raw_data=args.log_raw_data, serial=args.serial)`
`  File "/usr/local/lib/python3.7/dist-packages/decimctl/__init__.py", line 143, in __init__`
`    super(Device, self).__init__(mode='b')`
`  File "/usr/local/lib/python3.7/dist-packages/pylibftdi/device.py", line 190, in __init__`
`    self.open()`
`  File "/usr/local/lib/python3.7/dist-packages/decimctl/__init__.py", line 169, in open`
`    self._get_info()`
`  File "/usr/local/lib/python3.7/dist-packages/decimctl/__init__.py", line 152, in _get_info`
`    self.fdll.ftdi_usb_get_strings2.argtypes = self.fdll.ftdi_usb_get_strings.argtypes`
`  File "/usr/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__`
`    func = self.__getitem__(name)`
 ` File "/usr/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__`
`    func = self._FuncPtr((name_or_ordinal, self))`
`AttributeError: /lib/x86_64-linux-gnu/libftdi.so.1: undefined symbol: ftdi_usb_get_strings2`

maybe libftdi version is too old or new?
I'm used to work with linux but I don't know much python programming.
Had anybody any luck with a recent linux distribution?

**Comment by xenonheavyindustries** [comment]
Welp, I just took the time to read through this entire thread from initial request till now, and I am 100% in agreement with @quentinmit that this is something that needs addressing on Companion's side of things @haakonnessjoen 

I also would find this incredibly useful in my day to day work. As an aside, I think the idea of not implementing modules when they cant be guaranteed to work with every OS is not great. In these instances Companion should just denote, works with X and Y but not Z. etc

**Comment by IUT-andre-julie** [comment]
Hello everyone,

I'm working on MS W10 20H2 and I'm encountering an issue launching the decimctl.in order to control some DMON-6S.
The console is showing me this: 
![image](https://user-images.githubusercontent.com/66312427/118938801-51270a00-b94f-11eb-9dba-2d68492a1950.png)

I don't really understand the matter because I've got everything installed (e.g. : pylibftdi, libusb, ...) and the deccimctl has been well compiled with Pycharm.
![Compilation](https://user-images.githubusercontent.com/66312427/118939761-53d62f00-b950-11eb-8970-d0605fa9ac4b.PNG)
![interpretteur](https://user-images.githubusercontent.com/66312427/118939850-6b151c80-b950-11eb-8077-4cdf8102ea77.PNG)

If anyone could give me some hints please! Thanks a lot.

**Comment by quentinmit** [comment]
@IUT-andre-julie Your screenshot shows that you installed decimctl inside a venv, but you're trying to run it with the system python. You need to make sure you use the `python.exe` from within the venv. (Looks like from your screenshots that would be `..\venv\Scripts\python` perhaps?)

**Comment by xenonheavyindustries** [comment]
Gonna bump this and see if we can get some movement here @haakonnessjoen. Can we please accept that catering to lowest common denominator of interOS functionality is limiting? 

Alternatively @quentinmit were you able to roll an OSC based solution that would work on MacOS?

**Comment by krocheck** [comment]
@xenonheavyindustries implementing USB native instead of the IP-bridge approach that has been recommended multiple times by the maintainers is rather short-sighted and limiting.  As an example, for my setups I have various Decimator multiviews connected to different laptops' USB (which would be a pain to USB to a single machine for direct Companion control).  A bridge program would put those devices on the network via the computer they're connected to, allowing one or more Companion instances to control them.  It unfortunate that Decimator doesn't just put Ethernet on the products, but that's why they're so cheap.

And ... pull requests to add functionality are always welcome.  This is a community-driven, open-source project after all.  My involvement with the project started because I was tired of waiting around for a couple things to get added.  Just sayin'

**Comment by quentinmit** [comment]
I just don't want to implement a bespoke network protocol just for this module; if Companion is going to support remote hardware (which it should), that's something that should be supported for any device, not just a Decimator one.

I have not tried anything with OSC, though without feedback that wouldn't be super useful.

**Comment by QuentinBrown** [comment]
I'm assuming that in it's current state we can use the code that @quentinmit has written by triggering a shell script from companion in some way?
Given how long a route this has taken and that no resolution is timetabled, I am willing to make it work in my own installation via this route if that's possible.

Since this is a path being taken out of frustration and neither python nor Mac OS shell scripts are my thing and I imagine others are in the same boat, I wonder if anyone would be able to write up a little guide?

- I have installed python using the latest MacOS installer from the official python website (3.9). I have updated pip, setup tools and wheel, and installed homebrew but got stuck at installing decimctl. I was hoping _path/to/python -m pip install decimctl_ would do it and pull it from a repository somewhere but got a couple of errors: 
ERROR: Could not find a version that satisfies the requirement decimctl (from versions: none)
ERROR: No matching distribution found for decimctl

I'm not sure if maybe I need to download and run the code locally or if it should be available via the standard repository and just putting the name of it into pip or homebrew?

I'm  afraid we're going to need a bit of hand holding for ignorant newbies like m. Even better would be explanations of basic concepts surrounding the steps so when details change over time at least people can apply the logic and principles to figure out the new steps to get there.

Perhaps someone who has got this all working with companion would be kind enough to write something up?

**Comment by xenonheavyindustries** [comment]
@krocheck 
> ... is rather short-sighted and limiting....

any functionality is better than no functionality, vis a vis companion support, which is the current status quo. 

Further, for my needs, which are different than yours, USB control is actually strongly preferable, from a simplification and integration perspective. I need less devices in my mobile engineering rack, not more. 

So what you think of as short-sighted I think of as simpler and more elegant. It better meets my needs. Its often a good idea to assume others are not entirely clueless about their own needs. 

@quentinmit , understood I dont blame you.

**Comment by krocheck** [comment]
I wasn't impugning your specific setup or needs @xenonheavyindustries.  A middleware app to expose the Decimator via IP would work just the same for you having the device locally connected while allowing people with more complex setups to also take advantage of said implementation.  That's the gist of my comment.

**Comment by Stuart-Burton** [comment]
Following on from the excellent work by @quentinmit I have written a very simple python script for Raspberry Pi which hooks into his python module
https://github.com/Stuart-Burton/DeciMate
It provides a very simple way of taking HTTP GET requests formatted as commands for a Decimator.
So far tested with only one MD-CROSS V2

**Comment by Stuart-Burton** [comment]
Having now tried this with 4 devices I found that it has an issue and will only talk to 1. I will work on this further.

**Comment by Stuart-Burton** [comment]
Now tested and working with 3 x MD-Cross V2, issuing commands individually and to all 3 devices.

**Comment by Xtreemtec** [comment]
@Stuart-Burton  got some video of this?   Very intereseted to get this to work on a few Deci 12g-Cross units that are out of reach. 

Just not that good in linux / RPI..  So like to see it before diving deep into it to get this working. 
Thanks for the work and progress made so far.

**Comment by Stuart-Burton** [comment]
@Xtreemtec What video would you like? The unit in action or an installation video? I don't have access to the unit at the moment as it is in use switching 4 x MD-Cross v2 on a network TV studio job. I am working on providing a Raspberry Pi image that will have all the software installed and running at start up but I'm not really interested in making a demo video.

**Comment by Xtreemtec** [comment]
@Stuart-Burton   RPI Image is even better.   As i still seem to struggle with linux.  From a fulltime windows user it still is hard to get the grasps of line based OS.

**Comment by XENONChromatic** [comment]
It sure would be nice if the bitfocus folks would change their minds about integrating this as a module... being able to change layouts on a DMON would be lovely.

**Comment by josephdadams** [comment]
What module? This is just a way to control the device, no one ever wrote an actual module

**Comment by Stuart-Burton** [comment]
I still haven't forgotten about providing a Raspberry Pi image with all the heavy lifting done but as josephdadams says this is not a module, rather just a very specific way to control Decimator kit, which I might add has been working very well for our use case.

**Comment by josephdadams** [comment]
If you guys want me to make a companion module to work with @Stuart-Burton ’s Decimate, I am available for hire. My email is in my github profile.

**Comment by istnv** [comment]
I was working on a node version of decimctl but had to give the dmon back :(

**Comment by josephdadams** [comment]
Get this man a dmon!!

**Comment by Stuart-Burton** [comment]
I have produced a zipped Raspberry Pi image here:
https://drive.google.com/file/d/1tfq1l4AkkzEOqmPfLrSm2UpKXd576vdu/view?usp=sharing

On boot it runs up the HTTP server and provides the functionality as described here:
https://github.com/Stuart-Burton/DeciMate

The image requires about 2.5 Gig of SD card and can be expanded to a larger card by the use of raspi-config.

I've hosted the image on Google drive as it is 1.2 Gig compressed. Mods feel free to delete this post if external linking is against the rules.

**Comment by Keksstar** [comment]
With all this finished work, someone just need to write an Companion module for it?

Great work @Stuart-Burton ! :-)

**Comment by Toshiba01** [comment]
Has anyone made this script work on Windows? I have tried all the articles ( not so many) I could find on installing pylibftdi, libftdi and so on, used Zadig to even replace original drivers, but nothing works. In the best case I get to use "list" command other than that I get;

`C:\Users\Administrator\Desktop\decimctl-master\bin>python decimctl status
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\decimctl-master\bin\decimctl", line 118, in <module>
    main()
  File "C:\Users\Administrator\Desktop\decimctl-master\bin\decimctl", line 115, in main
    args.func(args)
  File "C:\Users\Administrator\Desktop\decimctl-master\bin\decimctl", line 26, in status
    d = _create_device(args)
  File "C:\Users\Administrator\Desktop\decimctl-master\bin\decimctl", line 19, in _create_device
    return decimctl.Device(log_raw_data=args.log_raw_data, serial=args.serial)
  File "C:\Python3.9\lib\site-packages\decimctl\__init__.py", line 150, in __init__
    super(Device, self).__init__(mode='b')
  File "C:\Python3.9\lib\site-packages\pylibftdi-0.20.0-py3.9.egg\pylibftdi\device.py", line 190, in __init__
    self.open()
  File "C:\Python3.9\lib\site-packages\decimctl\__init__.py", line 174, in open
    super(Device, self).open()
  File "C:\Python3.9\lib\site-packages\pylibftdi-0.20.0-py3.9.egg\pylibftdi\device.py", line 247, in open
    raise FtdiError(msg)
pylibftdi._base.FtdiError: b'usb_open() failed' (-4)`

I have tried with different Python versions but can't figure this out for the life of me. I have got it working straight away on my mac - windows doesn't seem to be as simple...

I'd be forever grateful to @quentinmit or anybody else that can point me in the right direction? Thanks!

**Comment by momosh13** [comment]
Hi, I'm trying to test this hex strings 
803043414d20312020202020202020202000
803043414d20310000000000000000000000
80 23 43 61 6d 20 31 20 20 20 20 20 20 20 20 20 20 20 1b 02 19 00
from " TSL Module #2 " and no luck, I bought this converter from amazon, using this software http://www.viewprotech.com/wap/index.php?ac=article&at=read&did=350
to send this commands, and the dmon-16 not responding any of this commands, please somebody help me. I'm trying find way to change the " Multi-Viewer Number of Windows" with RS-422/485. Thank you


![IMG_2622](https://github.com/bitfocus/companion-module-requests/assets/5689051/f6f96f87-5c72-4aa0-878c-80cd0dacf61c)

**Comment by Stuart-Burton** [comment]
@momosh13 RS422/485 is only available for TSL protocol for UMD and tally. The only way to change MV layouts is via the front panel or USB.

**Comment by momosh13** [comment]
Thank you for reply. There is any way you can give me one "example" hex string for RS422/485, for any setting, for testing purposes?

**Comment by Stuart-Burton** [comment]
The TSL protocol is available here:
https://tslproducts.com/media/1959/tsl-umd-protocol.pdf

**Comment by momosh13** [comment]
Thank you.

Anybody else may help me with working/tested hex string for DMON -16?
Please

**Comment by Keksstar** [comment]
Which communication parameters are set on your adapter?

**Comment by momosh13** [comment]
Thank you. I'm using as a RS485 converter 

<img width="325" alt="Pasted Graphic 2" src="https://github.com/bitfocus/companion-module-requests/assets/5689051/807c0968-fe42-417f-bffe-9a76d458e63a">

**Comment by Keksstar** [comment]
I meant baud rate parity, etc...

**Comment by momosh13** [comment]
I'm using Pin's  TXD+/A+ and TXD-/B-, I'm not sure, if the parameters can be set on this converter.
https://www.deshide.com/product-details.html?pid=303241&_t=1661495854

**Comment by momosh13** [comment]
RS 422/ RS 485
8 bit data
1 stop
even parity
38.4k baud

**Comment by Toshiba01** [comment]
For anyone wanting for this to work on Windows I have got a precompiled version for windows. Please use the README file for more details. This can also be used in companion with generic TCP module.
https://github.com/Toshiba01/DeciConn/

**Comment by allanclloyds** [comment]
Has anyone had any luck with DeciMate on the MD-HX firmware v1.7? I've got a few and they will at most display in the list and their status, but not changing settings.

**Comment by GeeJees** [comment]
> For anyone wanting for this to work on Windows I have got a precompiled version for windows. Please use the README file for more details. This can also be used in companion with generic TCP module. https://github.com/Toshiba01/DeciConn/

@Toshiba01 Where can I find the source or the precompiled version for Windows? There is only a readme file.
